// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC154_Dgl-bTlnnTN_V-Qxnjzp0m5jxNwA',
    appId: '1:861423827318:android:f099f96f8a35e7a8082257',
    messagingSenderId: '861423827318',
    projectId: 'tariqi-48165',
    storageBucket: 'tariqi-48165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtaDeJozlzhlpHo6p9vrrTcujx1zBoRs8',
    appId: '1:861423827318:ios:89c9b9abd0b3bb28082257',
    messagingSenderId: '861423827318',
    projectId: 'tariqi-48165',
    storageBucket: 'tariqi-48165.firebasestorage.app',
    iosBundleId: 'com.example.tariqi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtaDeJozlzhlpHo6p9vrrTcujx1zBoRs8',
    appId: '1:861423827318:ios:89c9b9abd0b3bb28082257',
    messagingSenderId: '861423827318',
    projectId: 'tariqi-48165',
    storageBucket: 'tariqi-48165.firebasestorage.app',
    iosBundleId: 'com.example.tariqi',
  );
}
